// Generated by CoffeeScript 1.6.3
/*
Redis Tagging

The MIT License (MIT)

Copyright © 2013 Patrick Liess, http://www.tcs.de

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var RedisInst, RedisTagging, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  RedisInst = require("redis");

  _ = require("underscore");

  RedisTagging = (function() {
    function RedisTagging(options) {
      var host, port;
      if (options == null) {
        options = {};
      }
      this._initErrors = __bind(this._initErrors, this);
      this._handleError = __bind(this._handleError, this);
      this._deleteID = __bind(this._deleteID, this);
      this.removebucket = __bind(this.removebucket, this);
      this.buckets = __bind(this.buckets, this);
      this.toptags = __bind(this.toptags, this);
      this.tags = __bind(this.tags, this);
      this.allids = __bind(this.allids, this);
      this.remove = __bind(this.remove, this);
      this.set = __bind(this.set, this);
      this.get = __bind(this.get, this);
      this.redisns = options.namespace || "rt";
      this.redisns = this.redisns + ":";
      port = options.port || 6379;
      host = options.host || "127.0.0.1";
      this.redis = RedisInst.createClient(port, host);
    }

    RedisTagging.prototype.get = function(options, cb) {
      var ns,
        _this = this;
      ns = this.redisns + options.bucket;
      this.redis.smembers("" + ns + ":ID:" + options.id, function(err, resp) {
        var tag, tags;
        if (err) {
          _this._handleError(cb, err);
          return;
        }
        tags = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = resp.length; _i < _len; _i++) {
            tag = resp[_i];
            _results.push(tag);
          }
          return _results;
        })();
        cb(null, tags);
      });
    };

    RedisTagging.prototype.set = function(options, cb) {
      var id_index, ns,
        _this = this;
      ns = this.redisns + options.bucket;
      options.score = options.score || 0;
      id_index = ns + ':ID:' + options.id;
      this._deleteID(ns, options.id, function(mc) {
        var tag, _i, _len, _ref;
        _ref = options.tags;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tag = _ref[_i];
          mc.push(['zincrby', ns + ':TAGCOUNT', 1, tag]);
          mc.push(['sadd', id_index, tag]);
          mc.push(['zadd', ns + ':TAGS:' + tag, options.score, options.id]);
        }
        if (options.tags.length) {
          mc.push(['sadd', ns + ':IDS', options.id]);
        }
        _this.redis.multi(mc).exec(function(err, resp) {
          if (err) {
            _this._handleError(cb, err);
            return;
          }
          cb(null, true);
        });
      });
    };

    RedisTagging.prototype.remove = function(options, cb) {
      var ns,
        _this = this;
      ns = this.redisns + options.bucket;
      this._deleteID(ns, options.id, function(mc) {
        if (!mc.length) {
          cb(null, true);
          return;
        }
        _this.redis.multi(mc).exec(function(err, resp) {
          if (err) {
            _this._handleError(cb, err);
            return;
          }
          cb(null, true);
        });
      });
    };

    RedisTagging.prototype.allids = function(options, cb) {
      var ns,
        _this = this;
      ns = this.redisns + options.bucket;
      this.redis.smembers(ns + ":IDS", function(err, resp) {
        if (err) {
          _this._handleError(cb, err);
          return;
        }
        cb(null, resp);
      });
    };

    RedisTagging.prototype.tags = function(options, cb) {
      var lastelement, mc, ns, prefix, resultkey, rndkey, tag, tagsresult, _keys,
        _this = this;
      ns = this.redisns + options.bucket;
      options = {
        tags: options.tags,
        limit: Number(options.limit || 100),
        offset: Number(options.offset || 0),
        withscores: Number(options.withscores) || 0,
        order: options.order === "asc" ? "" : "rev",
        type: (options.type || "inter").toLowerCase()
      };
      prefix = ns + ':TAGS:';
      lastelement = options.offset + options.limit - 1;
      mc = [];
      if (options.tags.length > 1) {
        rndkey = ns + (new Date().getTime()) + '_' + Math.floor(Math.random() * 9999999999);
        _keys = (function() {
          var _i, _len, _ref, _results;
          _ref = options.tags;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            tag = _ref[_i];
            _results.push(prefix + tag);
          }
          return _results;
        })();
        mc.push(['z' + options.type + 'store', rndkey, _keys.length].concat(_keys).concat(['AGGREGATE', 'MIN']));
        if (options.limit > 0) {
          resultkey = rndkey;
        }
      } else if (options.tags.length === 1) {
        mc.push(['zcard', prefix + options.tags[0]]);
        if (options.limit > 0) {
          resultkey = prefix + options.tags[0];
        }
      }
      if (mc.length === 0) {
        this._handleError(cb, "missingTags");
        return;
      }
      if (options.limit > 0) {
        tagsresult = ['z' + options.order + 'range', resultkey, options.offset, lastelement];
        if (options.withscores) {
          tagsresult = tagsresult.concat(['WITHSCORES']);
        }
        mc.push(tagsresult);
      }
      if (options.tags.length > 1) {
        mc.push(['del', rndkey]);
      }
      this.redis.multi(mc).exec(function(err, resp) {
        var e, i, rows;
        if (err) {
          _this._handleError(cb, err);
          return;
        }
        if (options.limit === 0) {
          rows = [];
        } else {
          rows = resp[1];
        }
        if (rows.length && options.withscores) {
          rows = (function() {
            var _i, _len, _results;
            _results = [];
            for (i = _i = 0, _len = rows.length; _i < _len; i = _i += 2) {
              e = rows[i];
              _results.push({
                id: e,
                score: rows[i + 1]
              });
            }
            return _results;
          })();
        }
        cb(null, {
          total_items: resp[0],
          items: rows,
          limit: options.limit,
          offset: options.offset
        });
      });
    };

    RedisTagging.prototype.toptags = function(options, cb) {
      var mc, ns, rediskey,
        _this = this;
      ns = this.redisns + options.bucket;
      options.amount = Math.abs(options.amount || 0) - 1;
      rediskey = ns + ':TAGCOUNT';
      mc = [["zcard", rediskey], ["zrevrange", rediskey, 0, options.amount, "WITHSCORES"]];
      this.redis.multi(mc).exec(function(err, resp) {
        var e, i, rows;
        if (err) {
          _this._handleError(cb, err);
          return;
        }
        rows = (function() {
          var _i, _len, _ref, _results;
          _ref = resp[1];
          _results = [];
          for (i = _i = 0, _len = _ref.length; _i < _len; i = _i += 2) {
            e = _ref[i];
            _results.push({
              tag: e,
              count: Number(resp[1][i + 1])
            });
          }
          return _results;
        })();
        cb(null, {
          total_items: resp[0],
          items: rows
        });
      });
    };

    RedisTagging.prototype.buckets = function(cb) {
      var _this = this;
      this.redis.keys(this.redisns + "*" + ":TAGCOUNT", function(err, resp) {
        var e, o;
        if (err) {
          _this._handleError(cb, err);
          return;
        }
        o = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = resp.length; _i < _len; _i++) {
            e = resp[_i];
            _results.push(e.substr(this.redisns.length, e.length - this.redisns.length - ":TAGCOUNT".length));
          }
          return _results;
        }).call(_this);
        cb(null, o);
      });
    };

    RedisTagging.prototype.removebucket = function(options, cb) {
      var _this = this;
      this.redis.keys(this.redisns + options.bucket + '*', function(err, resp) {
        if (err) {
          _this._handleError(cb, err);
          return;
        }
        if (resp.length) {
          _this.redis.del(resp, function(err, resp2) {
            cb(null, {
              ok: true,
              keys: resp
            });
          });
          return;
        }
        cb(null, {
          ok: true,
          keys: []
        });
      });
    };

    RedisTagging.prototype._deleteID = function(ns, id, cb) {
      var id_index, mc,
        _this = this;
      mc = [];
      id_index = ns + ':ID:' + id;
      this.redis.smembers(id_index, function(err, resp) {
        var tag, _i, _len;
        if (resp.length) {
          for (_i = 0, _len = resp.length; _i < _len; _i++) {
            tag = resp[_i];
            mc.push(['zincrby', ns + ':TAGCOUNT', -1, tag]);
            mc.push(['zrem', ns + ':TAGS:' + tag, id]);
          }
          mc.push(['del', id_index]);
          mc.push(['srem', ns + ':IDS', id]);
          mc.push(['zremrangebyscore', ns + ':TAGCOUNT', 0, 0]);
        }
        cb(mc);
      });
    };

    RedisTagging.prototype._handleError = function(cb, err, data) {
      var _err, _ref;
      if (data == null) {
        data = {};
      }
      if (_.isString(err)) {
        _err = new Error();
        _err.name = err;
        _err.message = ((_ref = this._ERRORS) != null ? typeof _ref[err] === "function" ? _ref[err](data) : void 0 : void 0) || "unkown";
      } else {
        _err = err;
      }
      cb(_err);
    };

    RedisTagging.prototype._initErrors = function() {
      var key, msg, _ref;
      this._ERRORS = {};
      _ref = this.ERRORS;
      for (key in _ref) {
        msg = _ref[key];
        this._ERRORS[key] = _.template(msg);
      }
    };

    RedisTagging.prototype.ERRORS = {
      "missingTags": "No tags supplied"
    };

    return RedisTagging;

  })();

  module.exports = RedisTagging;

}).call(this);
