on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run tests for package
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        redis-version: [4, 5, 6]

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: start redis ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: install dependencies
        run: npm ci
        env:
          CI: true

      - name: run tests
        run: npm test
        env:
          CI: true